### Numpy Mastery Assignment
- Answer all questions
- Submission : 20th September 2022

1. Create a 1D array of numbers from 0 to 9

In [3]:
import numpy as np

In [4]:
arr_1 = np.array([0,1,2,3,4,5,6,7,8,9])
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3x3 numpy of all True 

In [10]:
arr_2 = np.array([[True,True,True],[True,True,True],[True,True,True]])
arr_2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Create an array of numbers from 20 to 39

In [9]:
num = np.arange(20,40)
num

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

4. Replace all odd numbers in Q3 by -1

In [10]:
num[num % 2 ==1] = -1
num


array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38, -1])

5. Create two arrays of length 10 and print out  common items in both arrays

In [12]:
arr_1 = np.arange(1,11)
arr_1
arr_2 = np.arange(6,16)
arr_1
arr_2
common = np.intersect1d(arr_1, arr_2)
common

array([ 6,  7,  8,  9, 10])

6.  Create a 5x5 identity matrix

In [17]:
mat_1 = np.eye(3)
mat_1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [29]:
x = np.array ([10,12,9,2,20])
y = np.arange (10, 21)
z = np.ones((2,3))

print(x)
print(y)
print(z)

[10 12  9  2 20]
[10 11 12 13 14 15 16 17 18 19 20]
[[1. 1. 1.]
 [1. 1. 1.]]


8.Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [42]:
x_avg = np.average(x)
x_avg


2.047841614740048

In [ ]:
x_sd = np.std(x)

x = np.array([x_avg, x_sd])

9. Create a 10x10 array with random values and find the minimum and maximum values

In [43]:
arr = np.random.randint(low=0, high=100, size=(10, 10))
print(arr)

xmin, xmax = arr.min(), arr.max()
print("Min:", xmin, "Max:", xmax)

[[86 44 42 35  3 75 91 59 33 43]
 [33 16 16 81 44 74 92 90 43 56]
 [34  1 29 64 73 66 86  8 74 61]
 [82 16 12 37 42 14 91 80 52 91]
 [55 53 87 71 70 26 78 21 34 49]
 [ 5 33 58 12 91 88 21  3 83 61]
 [73  5 14 78 83 45 81 79 86 80]
 [27 46 88 19 92 24 31 32  7 48]
 [85 98 63 37 84 61 60 30 68 74]
 [36 99 99  8  7 12 42 32 21  7]]
Min: 1 Max: 99


10. Create a 3x3 matrix with values ranging from 0 to 8

In [44]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


11.  Generates an array [[1 2 3] [4 5 6]]

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


12. Generates an array [0 2.5 5 7.5 10]

In [47]:
arr = np.array([0,2.5,5,7.5,10])
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

13. Generates an 3x3 array of zeros

In [50]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

14. Create array from 0.1 to 10 with 12 elements, inclusively

In [51]:
arr = np.linspace(0.1,10,12)
arr

array([ 0.1,  1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1,
       10. ])

15. Create a matrix with seven columns and five rows of ten(10).

In [52]:
arr = np.full((5,7),10)
arr

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

16. What is the difference between numpy and list?

In [ ]:
 #NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays
# List is an in-built data structure to store multiple items in a single variable.

17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [55]:
arr = np.ones(50)
arr[0]=1
arr[1::2] = 0
arr

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [59]:
arr = np.eye(10)
arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [65]:
x = np.zeros((10,10))
np.fill_diagonal(x,1)
print(x)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [68]:
x = np.array ([[1,2],[3,4]])
y= np.array ([[5,6],[7,8]])
z = np.dot(x,y)

z 


array([[19, 22],
       [43, 50]])

21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [70]:
z = x*y
z

array([[ 5, 12],
       [21, 32]])

22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [71]:
d = 5
d * x

array([[ 5, 10],
       [15, 20]])

23. A = [[1,2],[3,4]] and B = transpose of A. Calculate AxB

In [77]:
A = np.array([[1,2],[3,4]])

B = np.transpose(A)

A*B

array([[ 1,  6],
       [ 6, 16]])

24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [83]:
A = np.array([[1,2],[3,4]]) 
B = np.array([[5,6],[7,8]])

C = A*B
D = B*A

# C IS EQUAL TO D

array([[ 5, 12],
       [21, 32]])

25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [102]:
arr = np.array([[0, 1, 2], [3, 4, 5]])

A = arr[0,:]
A
B = arr[1,:]
B
C = arr[0:,2]
C

array([2, 5])